# Generated by Django 5.1.6 on 2025-02-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Admission",
            new_name="StudentAdmission",
        ),
    ]
