# Generated by Django 5.1.6 on 2025-02-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_rename_admission_studentadmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentadmission",
            name="date_start",
            field=models.DateField(auto_now_add=True),
        ),
    ]
