# Generated by Django 5.1.6 on 2025-02-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0003_alter_studentadmission_date_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="fully_paid",
            field=models.BooleanField(default=False),
        ),
    ]
