# Generated by Django 5.1.6 on 2025-02-13 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_studentprofile_fully_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentadmission",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="student.studentprofile",
            ),
        ),
    ]
